### ISSUE TITLE
Dockerfile Create cmd - ad file output path

### ISSUE THREAD

**Issue by Emanuele94** [la-plas-growth/go-docker-ai#29]
Aggiungere la possibilità di specificare il percorso di creazione del file per il comando `Dockerfile`.
Ad esempio: `go-docker-ai-linux-amd64 Dockerfile -t golang -path /home/foo/bar`

**Comment by Allan-Nava** [comment]
It possible to add a new flag to handle the path @Emanuele94

**Comment by Allan-Nava** [comment]
Here is the fix https://github.com/la-plas-growth/go-docker-ai/pull/31 @Emanuele94 @Vincenzo-Pinto
